version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True



# Production ------

# version: '3'

# services:
#   web:
#     image: your_dockerhub_username/myapp:latest
#     ports:
#       - "8000:8000"
#     restart: always
#     environment:
#       - DJANGO_SETTINGS_MODULE=yourproject.settings
#     command: gunicorn yourproject.wsgi:application --bind 0.0.0.0:8000
