


# Production ------
version: '3'

services:
  web:
    image: harshad009/myapp:latest
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore_project.settings
    command: bash -c "python manage.py migrate && gunicorn bookstore_project.wsgi:application --bind 0.0.0.0:8000"


# simple -----
# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     environment:
#       - DEBUG=True
